services:
  strapi:
    build: .
    image: ${ECR_TREINAMENTOS_IMAGE}:${TAG_IMAGE}
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./strapi-base/public/uploads:/opt/app/public/uploads
    ports:
      - 1337:1337
    networks:
      - pg-network

networks:
  pg-network:
    driver: overlay
    external: true